name = "musicsync-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "musicsync-db"
database_id = "594657fc-6808-4340-a2c3-e4436ad232e2"
migrations_dir = "migrations"
